responses:
  200:
    description: "Success"
  201:
    description: "Created"
  204:
    description: "No Content"
  400:
    description: "Bad Request"
  401:
    description: "Unauthorized"
  403:
    description: "Forbidden"
  404:
    description: "Not Found"
  405:
    description: "Method Not Allowed"
  500:
    description: "Internal Server Error"
